"""Agent proposal interfaces and provider adapters."""

from powdrr_lift.workrr.actions import (
    WorkflowAction,
    WorkflowEdit,
    WorkflowFileEdits,
    WorkflowYamlOperation,
)
from powdrr_lift.workrr.coding_agent import (
    CODING_AGENT_ATTEMPT_SCHEMA_VERSION,
    CODING_AGENT_REQUEST_SCHEMA_VERSION,
    CodingAgentAttempt,
    CodingAgentAttemptStore,
    CodingAgentOutcome,
    CodingAgentProvider,
    CodingAgentRunner,
    CodingAgentStatus,
    ImplementationRequest,
    OpenCodePermissionPolicy,
    OpenCodeProvider,
    classify_coding_agent_attempt,
    run_coding_agent,
)
from powdrr_lift.workrr.coding_agent_validation import (
    CODING_AGENT_VALIDATION_REPORT_SCHEMA_VERSION,
    ValidationProfile,
    ValidationReport,
    ValidationReportStatus,
    ValidationResult,
    ValidationResultStatus,
    ValidationRunner,
    parse_validation_profile,
)
from powdrr_lift.workrr.context import WorkflowContext
from powdrr_lift.workrr.exchanges import ExchangeRecordingClient
from powdrr_lift.workrr.feature_endpoint import (
    FeatureEndpointConfig,
    FeatureEndpointResult,
    review_feature_diff,
    run_feature_endpoint,
    run_feature_in_place,
)
from powdrr_lift.workrr.loop import (
    WorkflowActionObservation,
    WorkflowActionOutcome,
    WorkflowActionProgressStrategy,
    WorkflowActionRequest,
    WorkflowExecutionObserver,
    WorkflowExecutionStrategy,
)
from powdrr_lift.workrr.progress import (
    ProgressDecision,
    WorkflowExecutionController,
    no_progress_feedback,
)
from powdrr_lift.workrr.protocol import (
    AgentClient,
    AgentProposalError,
    SchemaAwareWorkflowLLMClient,
    WorkflowLLMClient,
)
from powdrr_lift.workrr.provider_config import (
    LLMModelLimits,
    LLMModelMapping,
    LLMProviderDefinition,
    LLMProviderRole,
    LLMProviderRoles,
)
from powdrr_lift.workrr.repair import (
    RepairContext,
    RepairDirective,
    RepairExhaustionReport,
    RepairFailure,
    RepairFailureClass,
    RepairPolicy,
    RepairStage,
    classify_repair_failure,
)
from powdrr_lift.workrr.runner import ProposalKernel, run_proposal_round
from powdrr_lift.workrr.verification_provider import (
    VERIFICATION_PROVIDER_INVENTORY_SCHEMA_VERSION,
    ProviderExecutionResult,
    ProviderInventory,
    PytestVerificationProvider,
    VerificationProvider,
    VerificationProviderRegistry,
    VerificationProviderRequest,
    default_verification_provider_registry,
    discover_verification_inventory,
    match_selector,
)

__all__ = [
    "AgentClient",
    "AgentProposalError",
    "ExchangeRecordingClient",
    "FeatureEndpointConfig",
    "FeatureEndpointResult",
    "LLMModelLimits",
    "LLMModelMapping",
    "LLMProviderDefinition",
    "LLMProviderRole",
    "LLMProviderRoles",
    "SchemaAwareWorkflowLLMClient",
    "WorkflowAction",
    "WorkflowActionObservation",
    "WorkflowActionOutcome",
    "WorkflowActionProgressStrategy",
    "WorkflowActionRequest",
    "WorkflowEdit",
    "WorkflowFileEdits",
    "WorkflowLLMClient",
    "WorkflowYamlOperation",
    "ProposalKernel",
    "ProgressDecision",
    "RepairContext",
    "RepairDirective",
    "RepairExhaustionReport",
    "RepairFailure",
    "RepairFailureClass",
    "RepairPolicy",
    "RepairStage",
    "classify_repair_failure",
    "no_progress_feedback",
    "run_proposal_round",
    "review_feature_diff",
    "run_feature_in_place",
    "run_feature_endpoint",
    "WorkflowExecutionController",
    "WorkflowExecutionObserver",
    "WorkflowExecutionStrategy",
    "WorkflowContext",
    "CODING_AGENT_ATTEMPT_SCHEMA_VERSION",
    "CODING_AGENT_REQUEST_SCHEMA_VERSION",
    "CodingAgentAttempt",
    "CodingAgentAttemptStore",
    "CodingAgentOutcome",
    "CodingAgentProvider",
    "CodingAgentRunner",
    "CodingAgentStatus",
    "ImplementationRequest",
    "OpenCodePermissionPolicy",
    "OpenCodeProvider",
    "classify_coding_agent_attempt",
    "run_coding_agent",
    "CODING_AGENT_VALIDATION_REPORT_SCHEMA_VERSION",
    "ValidationProfile",
    "ValidationReport",
    "ValidationReportStatus",
    "ValidationResult",
    "ValidationResultStatus",
    "ValidationRunner",
    "parse_validation_profile",
    "ProviderExecutionResult",
    "ProviderInventory",
    "PytestVerificationProvider",
    "VERIFICATION_PROVIDER_INVENTORY_SCHEMA_VERSION",
    "VerificationProvider",
    "VerificationProviderRegistry",
    "VerificationProviderRequest",
    "default_verification_provider_registry",
    "discover_verification_inventory",
    "match_selector",
]
