"""Core package exports."""

# ruff: noqa: F401

from typing import Any

from powdrr_lift.core.architecture_specification import (
    ArchitectureSpecificationValidationIssue,
    ArchitectureSpecificationValidationReport,
    architecture_specification_default_output_path,
    build_architecture_specification_validation_report,
    create_architecture_specification_template,
    render_architecture_specification_template,
    validate_architecture_specification_yaml,
)
from powdrr_lift.core.blame_view import (
    BlameChunk,
    BlameFileView,
    BlameLine,
    BlameProvenance,
    BlameViewState,
    RepoTreeNode,
    blame_file_view_to_data,
    blame_tree_node_to_data,
    blame_view_state_to_data,
    build_blame_file_view,
    build_blame_view_state,
    build_repo_tree,
)
from powdrr_lift.core.code_index import (
    BranchState,
    code_index_db_path,
    lookup_code_provenance,
    lookup_code_provenance_span,
    refresh_code_index,
)
from powdrr_lift.core.codebase_state import (
    CodebaseStateDecision,
    CodebaseStateEntity,
    CodebaseStateIntent,
    CodebaseStateLifecycleItem,
    CodebaseStateRelationship,
    CodebaseStateReport,
    CodebaseStateSource,
    build_codebase_state_report,
    build_current_decisions_report,
    build_invariants_report,
    codebase_state_default_output_path,
    create_codebase_state,
    create_current_state_specification,
    current_state_specification_default_output_path,
    render_codebase_state_report,
    render_current_decisions_report,
    render_current_state_specification_report,
    render_invariants_report,
)
from powdrr_lift.core.edit_context import (
    EditContextLine,
    EditContextRange,
    EditContextReport,
    lookup_edit_context,
    parse_line_range,
    parse_line_ranges,
    render_edit_context_report,
)
from powdrr_lift.core.entity_context import (
    EntityDecisionOccurrence,
    EntityDecisionReport,
    EntityReferenceReport,
    EntityRelationshipReport,
    lookup_entity_decisions,
    lookup_entity_references,
    lookup_entity_relationships,
    render_entity_decision_report,
    render_entity_reference_report,
    render_entity_relationship_report,
)
from powdrr_lift.core.feature_planning_specification import (
    create_feature_pr_specification_template,
    create_system_map_specification_template,
    feature_pr_specification_default_output_path,
    render_feature_pr_specification_template,
    render_system_map_specification_template,
    start_planning_feature,
    system_map_specification_default_output_path,
)
from powdrr_lift.core.implementation_specification import (
    ImplementationSpecificationValidationIssue,
    ImplementationSpecificationValidationReport,
    build_implementation_specification_validation_report,
    create_implementation_specification_template,
    implementation_specification_default_output_path,
    render_implementation_specification_template,
    validate_implementation_specification_yaml,
)
from powdrr_lift.core.index import (
    ChangelogDocument,
    EntityGraph,
    EntityOccurrence,
    ProvenanceRecord,
    RelationshipOccurrence,
    SourceIndex,
    build_changelog_index,
    build_changelog_index_at_ref,
)
from powdrr_lift.core.plan_diff_specification import (
    build_plan_diff_report,
    create_plan_diff_specification,
    plan_diff_specification_default_output_path,
    render_plan_diff_specification,
)
from powdrr_lift.core.pr_analysis import (
    BranchDiffEntry,
    collect_branch_diff_entries,
    resolve_default_branch,
    resolve_repo_root,
)
from powdrr_lift.core.pr_specification import (
    ProposedPRSearchReport,
    ProposedPRSearchResult,
    PRSpecificationValidationIssue,
    PRSpecificationValidationReport,
    build_pr_specification_validation_report,
    create_pr_specification_template,
    pr_specification_default_output_path,
    proposed_pr_specification_path,
    render_pr_specification_template,
    render_proposed_pr_search_report,
    search_proposed_pr_specifications,
    show_proposed_pr_specification,
    validate_pr_specification_yaml,
)
from powdrr_lift.core.schemas import (
    ChangeEntity,
    ChangeEntityRelationship,
    ChangeFeatureState,
    ChangeFile,
    ChangeGuidance,
    ChangeInvariant,
    ChangeLog,
    ChangeProposedPRState,
    Decision,
    Intent,
    RelatedSection,
    Span,
    parse_change_log,
)
from powdrr_lift.core.system_specification import (
    SystemSpecificationValidationIssue,
    SystemSpecificationValidationReport,
    build_system_specification_validation_report,
    create_system_specification_template,
    render_system_specification_template,
    system_specification_default_output_path,
    validate_system_specification_yaml,
)
from powdrr_lift.core.template import (
    create_change_log_template,
    create_change_log_template_from_plan_diff,
    render_change_log_template,
)
from powdrr_lift.core.workflow_task_specification import (
    TaskComplexity,
    TaskStatus,
    WorkflowTask,
    WorkflowTaskDocument,
    WorkflowTaskValidationIssue,
    WorkflowTaskValidationReport,
    build_workflow_task_directory_validation_report,
    build_workflow_task_validation_report,
    load_workflow_task_document,
    load_workflow_task_documents,
    load_workflow_tasks,
    save_workflow_task,
    save_workflow_task_document,
    select_ready_workflow_tasks,
    validate_workflow_task_directory,
    validate_workflow_task_directory_json,
    validate_workflow_task_json,
    validate_workflow_task_json_file,
    workflow_task_document_from_data,
    workflow_task_document_from_json,
    workflow_task_document_to_json,
    workflow_task_from_data,
    workflow_task_from_json,
    workflow_task_to_json,
)
from powdrr_lift.core.workflow_template_specification import (
    WorkflowTaskTemplate,
    WorkflowTaskTemplateGeneration,
    WorkflowTemplate,
    WorkflowTemplateDocument,
    WorkflowTemplateValidationIssue,
    WorkflowTemplateValidationReport,
    build_workflow_template_validation_report,
    load_workflow_template,
    save_workflow_template,
    validate_workflow_template_json,
    validate_workflow_template_json_file,
    workflow_template_from_data,
    workflow_template_from_json,
    workflow_template_to_json,
)

_ARCHITECTURE = "powdrr_lift.core.architecture_specification"
_BLAME_VIEW = "powdrr_lift.core.blame_view"
_CODEBASE_STATE = "powdrr_lift.core.codebase_state"
_CODE_INDEX = "powdrr_lift.core.code_index"
_EDIT_CONTEXT = "powdrr_lift.core.edit_context"
_ENTITY_CONTEXT = "powdrr_lift.core.entity_context"
_FEATURE_PLANNING = "powdrr_lift.core.feature_planning_specification"
_IMPLEMENTATION = "powdrr_lift.core.implementation_specification"
_INDEX = "powdrr_lift.core.index"
_PR_ANALYSIS = "powdrr_lift.core.pr_analysis"
_PR_SPECIFICATION = "powdrr_lift.core.pr_specification"
_SCHEMAS = "powdrr_lift.core.schemas"
_SYSTEM = "powdrr_lift.core.system_specification"
_TEMPLATE = "powdrr_lift.core.template"
_VALIDATE = "powdrr_lift.core.validate"
_WORKFLOW_TASK_SPECIFICATION = "powdrr_lift.core.workflow_task_specification"
_WORKFLOW_TEMPLATE_SPECIFICATION = "powdrr_lift.core.workflow_template_specification"

_EXPORTS: dict[str, str] = {
    "BranchDiffEntry": _PR_ANALYSIS,
    "BranchState": _CODE_INDEX,
    "BlameChunk": _BLAME_VIEW,
    "BlameFileView": _BLAME_VIEW,
    "BlameLine": _BLAME_VIEW,
    "BlameProvenance": _BLAME_VIEW,
    "BlameViewState": _BLAME_VIEW,
    "RepoTreeNode": _BLAME_VIEW,
    "ArchitectureSpecificationValidationIssue": _ARCHITECTURE,
    "ArchitectureSpecificationValidationReport": _ARCHITECTURE,
    "ImplementationSpecificationValidationIssue": _IMPLEMENTATION,
    "ImplementationSpecificationValidationReport": _IMPLEMENTATION,
    "SystemSpecificationValidationIssue": _SYSTEM,
    "SystemSpecificationValidationReport": _SYSTEM,
    "TaskComplexity": _WORKFLOW_TASK_SPECIFICATION,
    "TaskStatus": _WORKFLOW_TASK_SPECIFICATION,
    "PRSpecificationValidationIssue": _PR_SPECIFICATION,
    "PRSpecificationValidationReport": _PR_SPECIFICATION,
    "ProposedPRSearchReport": _PR_SPECIFICATION,
    "ProposedPRSearchResult": _PR_SPECIFICATION,
    "WorkflowTask": _WORKFLOW_TASK_SPECIFICATION,
    "WorkflowTaskDocument": _WORKFLOW_TASK_SPECIFICATION,
    "WorkflowTaskValidationIssue": _WORKFLOW_TASK_SPECIFICATION,
    "WorkflowTaskValidationReport": _WORKFLOW_TASK_SPECIFICATION,
    "WorkflowTaskTemplate": _WORKFLOW_TEMPLATE_SPECIFICATION,
    "WorkflowTaskTemplateGeneration": _WORKFLOW_TEMPLATE_SPECIFICATION,
    "WorkflowTemplate": _WORKFLOW_TEMPLATE_SPECIFICATION,
    "WorkflowTemplateDocument": _WORKFLOW_TEMPLATE_SPECIFICATION,
    "WorkflowTemplateValidationIssue": _WORKFLOW_TEMPLATE_SPECIFICATION,
    "WorkflowTemplateValidationReport": _WORKFLOW_TEMPLATE_SPECIFICATION,
    "proposed_pr_specification_path": _PR_SPECIFICATION,
    "CodebaseStateDecision": _CODEBASE_STATE,
    "CodebaseStateEntity": _CODEBASE_STATE,
    "CodebaseStateIntent": _CODEBASE_STATE,
    "CodebaseStateLifecycleItem": _CODEBASE_STATE,
    "CodebaseStateRelationship": _CODEBASE_STATE,
    "CodebaseStateReport": _CODEBASE_STATE,
    "CodebaseStateSource": _CODEBASE_STATE,
    "build_current_state_specification_report": _CODEBASE_STATE,
    "EditContextLine": _EDIT_CONTEXT,
    "EditContextRange": _EDIT_CONTEXT,
    "EditContextReport": _EDIT_CONTEXT,
    "EntityDecisionOccurrence": _ENTITY_CONTEXT,
    "EntityDecisionReport": _ENTITY_CONTEXT,
    "EntityReferenceReport": _ENTITY_CONTEXT,
    "EntityRelationshipReport": _ENTITY_CONTEXT,
    "ChangelogDocument": _INDEX,
    "ChangeEntity": _SCHEMAS,
    "ChangeEntityRelationship": _SCHEMAS,
    "ChangeFeatureState": _SCHEMAS,
    "ChangeFile": _SCHEMAS,
    "ChangeGuidance": _SCHEMAS,
    "ChangeInvariant": _SCHEMAS,
    "ChangeLog": _SCHEMAS,
    "ChangeProposedPRState": _SCHEMAS,
    "Decision": _SCHEMAS,
    "EntityGraph": _INDEX,
    "EntityOccurrence": _INDEX,
    "Intent": _SCHEMAS,
    "RelatedSection": _SCHEMAS,
    "Span": _SCHEMAS,
    "SourceIndex": _INDEX,
    "ProvenanceRecord": _INDEX,
    "RelationshipOccurrence": _INDEX,
    "ValidationIssue": _VALIDATE,
    "ValidationReport": _VALIDATE,
    "architecture_specification_default_output_path": _ARCHITECTURE,
    "blame_file_view_to_data": _BLAME_VIEW,
    "blame_tree_node_to_data": _BLAME_VIEW,
    "blame_view_state_to_data": _BLAME_VIEW,
    "build_architecture_specification_validation_report": _ARCHITECTURE,
    "build_blame_file_view": _BLAME_VIEW,
    "build_blame_view_state": _BLAME_VIEW,
    "build_codebase_state_report": _CODEBASE_STATE,
    "build_current_decisions_report": _CODEBASE_STATE,
    "build_invariants_report": _CODEBASE_STATE,
    "build_implementation_specification_validation_report": _IMPLEMENTATION,
    "build_pr_specification_validation_report": _PR_SPECIFICATION,
    "build_system_specification_validation_report": _SYSTEM,
    "build_workflow_task_directory_validation_report": _WORKFLOW_TASK_SPECIFICATION,
    "build_workflow_task_validation_report": _WORKFLOW_TASK_SPECIFICATION,
    "build_changelog_index": _INDEX,
    "build_changelog_index_at_ref": _INDEX,
    "build_repo_tree": _BLAME_VIEW,
    "code_index_db_path": _CODE_INDEX,
    "codebase_state_default_output_path": _CODEBASE_STATE,
    "current_state_specification_default_output_path": _CODEBASE_STATE,
    "collect_branch_diff_entries": _PR_ANALYSIS,
    "create_architecture_specification_template": _ARCHITECTURE,
    "create_change_log_template": _TEMPLATE,
    "create_change_log_template_from_plan_diff": _TEMPLATE,
    "create_codebase_state": _CODEBASE_STATE,
    "create_feature_pr_specification_template": _FEATURE_PLANNING,
    "create_current_state_specification": _CODEBASE_STATE,
    "create_implementation_specification_template": _IMPLEMENTATION,
    "create_pr_specification_template": _PR_SPECIFICATION,
    "create_system_map_specification_template": _FEATURE_PLANNING,
    "create_system_specification_template": _SYSTEM,
    "start_planning_feature": _FEATURE_PLANNING,
    "implementation_specification_default_output_path": _IMPLEMENTATION,
    "lookup_code_provenance": _CODE_INDEX,
    "lookup_code_provenance_span": _CODE_INDEX,
    "lookup_edit_context": _EDIT_CONTEXT,
    "lookup_entity_decisions": _ENTITY_CONTEXT,
    "lookup_entity_references": _ENTITY_CONTEXT,
    "lookup_entity_relationships": _ENTITY_CONTEXT,
    "load_workflow_tasks": _WORKFLOW_TASK_SPECIFICATION,
    "load_workflow_task_document": _WORKFLOW_TASK_SPECIFICATION,
    "load_workflow_task_documents": _WORKFLOW_TASK_SPECIFICATION,
    "parse_change_log": _SCHEMAS,
    "parse_line_range": _EDIT_CONTEXT,
    "parse_line_ranges": _EDIT_CONTEXT,
    "parse_validation_report": _VALIDATE,
    "pr_specification_default_output_path": _PR_SPECIFICATION,
    "refresh_code_index": _CODE_INDEX,
    "render_architecture_specification_template": _ARCHITECTURE,
    "render_codebase_state_report": _CODEBASE_STATE,
    "render_current_state_specification_report": _CODEBASE_STATE,
    "render_current_decisions_report": _CODEBASE_STATE,
    "render_edit_context_report": _EDIT_CONTEXT,
    "render_feature_pr_specification_template": _FEATURE_PLANNING,
    "render_entity_decision_report": _ENTITY_CONTEXT,
    "render_entity_reference_report": _ENTITY_CONTEXT,
    "render_entity_relationship_report": _ENTITY_CONTEXT,
    "render_implementation_specification_template": _IMPLEMENTATION,
    "render_invariants_report": _CODEBASE_STATE,
    "render_pr_specification_template": _PR_SPECIFICATION,
    "render_proposed_pr_search_report": _PR_SPECIFICATION,
    "render_system_map_specification_template": _FEATURE_PLANNING,
    "render_system_specification_template": _SYSTEM,
    "render_change_log_template": _TEMPLATE,
    "resolve_default_branch": _PR_ANALYSIS,
    "resolve_repo_root": _PR_ANALYSIS,
    "search_proposed_pr_specifications": _PR_SPECIFICATION,
    "show_proposed_pr_specification": _PR_SPECIFICATION,
    "save_workflow_task_document": _WORKFLOW_TASK_SPECIFICATION,
    "save_workflow_task": _WORKFLOW_TASK_SPECIFICATION,
    "select_ready_workflow_tasks": _WORKFLOW_TASK_SPECIFICATION,
    "build_workflow_template_validation_report": _WORKFLOW_TEMPLATE_SPECIFICATION,
    "system_specification_default_output_path": _SYSTEM,
    "system_map_specification_default_output_path": _FEATURE_PLANNING,
    "validate_architecture_specification_yaml": _ARCHITECTURE,
    "build_validation_report": _VALIDATE,
    "validate_change_log_yaml": _VALIDATE,
    "validate_implementation_specification_yaml": _IMPLEMENTATION,
    "validate_pr_specification_yaml": _PR_SPECIFICATION,
    "validate_system_specification_yaml": _SYSTEM,
    "validate_workflow_task_directory": _WORKFLOW_TASK_SPECIFICATION,
    "validate_workflow_task_directory_json": _WORKFLOW_TASK_SPECIFICATION,
    "validate_workflow_task_json": _WORKFLOW_TASK_SPECIFICATION,
    "validate_workflow_task_json_file": _WORKFLOW_TASK_SPECIFICATION,
    "validate_workflow_template_json": _WORKFLOW_TEMPLATE_SPECIFICATION,
    "validate_workflow_template_json_file": _WORKFLOW_TEMPLATE_SPECIFICATION,
    "workflow_task_from_data": _WORKFLOW_TASK_SPECIFICATION,
    "workflow_task_from_json": _WORKFLOW_TASK_SPECIFICATION,
    "workflow_task_to_json": _WORKFLOW_TASK_SPECIFICATION,
    "workflow_task_document_from_data": _WORKFLOW_TASK_SPECIFICATION,
    "workflow_task_document_from_json": _WORKFLOW_TASK_SPECIFICATION,
    "workflow_task_document_to_json": _WORKFLOW_TASK_SPECIFICATION,
    "workflow_template_from_data": _WORKFLOW_TEMPLATE_SPECIFICATION,
    "workflow_template_from_json": _WORKFLOW_TEMPLATE_SPECIFICATION,
    "workflow_template_to_json": _WORKFLOW_TEMPLATE_SPECIFICATION,
}

__all__ = sorted(_EXPORTS)


def __getattr__(name: str) -> Any:
    if name in {
        "ValidationIssue",
        "ValidationReport",
        "build_validation_report",
        "parse_validation_report",
        "validate_change_log_yaml",
    }:
        from powdrr_lift.core.validate import (
            ValidationIssue,
            ValidationReport,
            build_validation_report,
            parse_validation_report,
            validate_change_log_yaml,
        )

        return {
            "ValidationIssue": ValidationIssue,
            "ValidationReport": ValidationReport,
            "build_validation_report": build_validation_report,
            "parse_validation_report": parse_validation_report,
            "validate_change_log_yaml": validate_change_log_yaml,
        }[name]

    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
